### ISSUE TITLE
Index out of bounds  while trying to sync from/to NC 14 w/ bookmarks App 0.14

### ISSUE THREAD

**Issue by tkurbad** [marcelklehr/floccus#200]
### Software versions

* Browser: Chromium 69.0.3497.81 (Gentoo Linux)
* Nextcloud: 14.0.3.0
* Nextcloud Bookmarks app: 0.14.2
* Floccus: 3.1.7

### Steps to reproduce

1. Nextcloud Bookmarks are populated with around 2200 bookmarks from another computer
2. Trying to merge local and NC bookmarks using the "reset cache" option. There is, however, a large common subset of local and NC bookmarks, since browsers have been synchronized before using the infamous xmarks.

### Expected outcome

Sync should progress to the end. Additional server bookmarks should appear locally in browser, additional local bookmarks should be stored on server.

### Actual outcome

Sync fails after a while with the error message "Index out of bounds" (sometimes printed several times).

Not checking "reset cache" doesn't make a difference. (Only sync takes longer and there are at least 20 "Index out of bounds" errors shown at once in the end).

**Comment by tkurbad** [comment]
Debug log: https://gist.github.com/tkurbad/0eb1763328e67a9924ec1a44964b8ebe

It seems to always fail in the same place.

**Comment by marcelklehr** [comment]
Thank you for the detailed report. The error may present due to a recent change I made to increase performance. I've just released a bugfix release. Could you try it again once you've received the update?

**Comment by tkurbad** [comment]
Thank you for the fast response.

The error just appeared again. However, sync automatically restarted, so I'll give it a (few) runs more and will update my findings...

**Comment by tkurbad** [comment]
Okay, I now got "Index out of bounds" and "QUOTA_BYTES quota exceeded". :-(

**Comment by marcelklehr** [comment]
Thanks so much. I was able to isolate, reproduce and fix the bug. Just released a new version.

**Comment by tkurbad** [comment]
Sorry @marcelklehr, but I'm still getting the "Index out of bounds" error. Debug log again? ;-)

**Comment by tkurbad** [comment]
New debug.log: https://gist.github.com/tkurbad/554cc5edf927ccfb6d35bb2a64627501

**Comment by marcelklehr** [comment]
Wow, your bookmarks are a goldmine for finding bugs! :)
This one is the same error but a different cause. Should be fixed now, as well.

**Comment by tkurbad** [comment]
And once again: https://gist.github.com/tkurbad/aad2e4b6be6bebbd01b31388b1c750dc

This time, however, I got a folder and contents locally that previously only existed on the NC server. So, we are making visible progress! ;-)

**Comment by marcelklehr** [comment]
This is amazing :scream_cat: I've never fixed so many bugs from one report before :D

**Comment by marcelklehr** [comment]
Bugfix release is out. :)

**Comment by tkurbad** [comment]
Keep'em bugfixes comin'! ;-)

New debug.log (still "Index out of bounds"): https://gist.github.com/tkurbad/bbf67a4a89a701a7ccd87455b3737456

**Comment by marcelklehr** [comment]
mmh. I think this log was cut off. Possibly by chrome's quota. Can you clear the logs again and capture a new log?

**Comment by tkurbad** [comment]
> mmh. I think this log was cut off. Possibly by chrome's quota. Can you clear the logs again and capture a new log?

Actually, it seems to be a problem with gist. Log is now in this OC-share: https://owncloud.iwm-tuebingen.de/s/n8povKTwgGLqYTy

**Comment by marcelklehr** [comment]
Fix is out... ;D

**Comment by tkurbad** [comment]
Thanks! I'm afk at the moment. Will check tomorrow morning.

**Comment by tkurbad** [comment]
@marcelklehr Are you still with me? ;-)

**Comment by marcelklehr** [comment]
Yes! I'm with you. I've been tending to other issues as well, though, so I haven't published another bugfix release yet, but this is your fix: https://github.com/marcelklehr/floccus/commit/f2ec29edb618e45c79ffa7c819a68857400851ca :D

**Comment by marcelklehr** [comment]
v3.1.14 has been released, your turn @tkurbad :D

**Comment by marcelklehr** [comment]
ooph. :tada:

You're welcome :D

**Comment by onny** [comment]
Hey @marcelklehr thank you for this nice extension! I'm getting the same error in `brave 0.57.18` and `nextcloud 15.0.0` with `bookmarks app 0.14.3`, see the log here:
https://onny.project-insanity.org/files/floccus-3.2.0-2018-12-22%20(1).log
