### ISSUE TITLE
Nextcloud 10.0.3 with ssl -> Chromium-> Floccus not synching

### ISSUE THREAD

**Issue by SISolutions** [marcelklehr/floccus#31]
I have installed Floccus to 
Chromium : Version 61.0.3163.100 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
Firefox : Version 56 running on Ubuntu 16.04 (64-bit)
Nextcloud 10.0.5  with official ssl certificate (eg. https://mync.work.gr:port) and the app is not working. The bookmarks never get synched nothing happens -> It says synching...  and never ending or at least give an error.
I am the admin of the installation and i know that everytning else working fine.

**Comment by marcelklehr** [comment]
Hi @SISolutions,
which version of floccus did you install? Can you see an Owncloud/Nextcloud bookmarks folder somewhere in your bookmarks? What doo you see if you close and reopen the floccus pop-up?
In any case: Could you follow the debugging steps provided over here: https://github.com/marcelklehr/floccus/issues/27 You may also want to check out the network tab in the debugger to see what is happening to the network request on sync.

**Comment by SISolutions** [comment]
1) version 1.3.0
2) No i cant see any folder
3) see attachment says synching but nothing happens
4) close and reopen floccus i see the same like in the attachment
5) force sync is disabled

**Comment by SISolutions** [comment]
Sorry but could FIND HOW TO copy the damn thing

![screenshot from 2017-10-11 14-49-36](https://user-images.githubusercontent.com/10695841/31439102-97de8510-ae93-11e7-8446-e37b1ea1ce87.png)

**Comment by marcelklehr** [comment]
Ok, I think I know what the problem is, even though I'd have needed the 'console' tab's content, rather than the 'inspector' tab's... My bad on that part. :)

**Comment by marcelklehr** [comment]
Should be fixed in [v1.3.0-beta.4](https://github.com/marcelklehr/floccus/releases/tag/v1.3.0-beta.4). Reopen, or shout if it isn't :)

**Comment by marcelklehr** [comment]
(Note, you'll probably need to delete the account you created in floccus, and create a new one, so that force sync becomes clickable again. This will not be necessary for future connection failures, though, as I fixed this as well.)

**Comment by SISolutions** [comment]
Good morning.
Thank you my friend. Will try it immediately and reply to you the results.
QUESTION:
If i will use it at two different browsers (firefox,chromium) will the bookmarks be saved to two separate folders? or they all be merged in one?

Thank you for the quick response and keep up your good project.

**Comment by SISolutions** [comment]
Installed the beta4 but still no connection. Not working

Console 

extensions.js:2725 [Deprecation] /deep/ combinator is no longer supported in CSS dynamic profile. It is now effectively no-op, acting as if it were a descendant combinator. You should consider to remove it. See https://www.chromestatus.com/features/4964279606312960 for more details.
scrollToWrapper_ @ extensions.js:2725

**Comment by SISolutions** [comment]
Still have issue

![screenshot from 2017-10-12 16-52-34](https://user-images.githubusercontent.com/10695841/31499617-f8682870-af6d-11e7-966d-3c9d1baf8d76.png)

**Comment by marcelklehr** [comment]
Aha. But we're getting somewhere. Apparently, there's a parse error happening :/ Could you go to the network tab in the inspector and inspect the last request to the bookmark endpoint? The should be a tab displaying the response data.

**Comment by SISolutions** [comment]
![screenshot from 2017-10-12 23-28-55](https://user-images.githubusercontent.com/10695841/31517843-cd738abe-afa5-11e7-9ed4-06a9b74479a1.png)

**Comment by marcelklehr** [comment]
ok, my bad again. You ended up in the wrong inspector, it seems. Sorry.

Here are the updated steps you can follow:

* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* leave the inspector open and go to floccus options and make sure the account of your choice is connected
* trigger a sync by clicking on `force Sync` for the account of your choice
* go back to the inspector window and copy the logs from the console tab after waiting approx. 1min
* paste the log here, after making sure that there is no more sensitive data in there (there most probably will be)
* go to the network tab in the inspector and click on the last row that says `bookmarks`, then click on `response` in the panel that opens and copy the data, paste it here after once again making sure that there is no more sensitive information in there

**Comment by SISolutions** [comment]
1) enable Developer mode -> i have only developer toos i cant find what you suggesting
2) click on dist/html/background.html button in floccus' entry next to "Inspect views: " -> i cant find this anywhere (look pic attachment to see what i see)
![screenshot from 2017-10-13 10-20-38](https://user-images.githubusercontent.com/10695841/31534619-62d779da-b000-11e7-8c36-bed5e8c51530.png)

**Comment by marcelklehr** [comment]
![untitled](https://user-images.githubusercontent.com/986878/31538811-04645056-b007-11e7-809b-a06cd49ffab1.png)
;)

**Comment by SISolutions** [comment]
![screenshot from 2017-10-14 00-02-37](https://user-images.githubusercontent.com/10695841/31566434-4287b596-b073-11e7-9e73-1b014a478262.png)

**Comment by SISolutions** [comment]
floccus couldn't connect
![screenshot from 2017-10-14 00-09-04](https://user-images.githubusercontent.com/10695841/31566686-71c46e8e-b074-11e7-9e37-5eff8a4c2a29.png)

waited for some minutes but console doesnt show anything

**Comment by SISolutions** [comment]
To show you that my MC instance is working with no problems and floccus error. There is no movement as i see in the network or console.


![screenshot from 2017-10-15 16-31-13](https://user-images.githubusercontent.com/10695841/31585198-9ba7dbac-b1c6-11e7-9de5-ff4e6fa4a469.png)

**Comment by marcelklehr** [comment]
Just to make sure: if force sync is greyed out, there'll likely be no movement in the network monitor -- Did you delete the account and set up a new one?

**Comment by SISolutions** [comment]
Yes deleted and created many times. And from different browsers and places too (home & office).

**Comment by SISolutions** [comment]
any news?

**Comment by marcelklehr** [comment]
Mh. very strange. Would you perhaps be able to provide me with a test account on your instance? Then I could try some more explorative testing on my machine. Just drop me a mail. :)

**Comment by SISolutions** [comment]
https://nc.revoil.gr:11611

username: marcel
password: floccus

will be valid for 3 days.

Thank you.

John P

**Comment by marcelklehr** [comment]
Thanks, this was very helpful. It seems, the request to the bookmark endpoint is redirected to the nextcloud login page, on your instance. This could indicate that you're using an older version of the nc bookmarks app. Or nextcloud 10 doesn't allow basic auth, but that would be very weird. You could try checking the apps section in the nextcloud admin panel and making sure bookmarks is up to date. Also, have a look at the nextcloud logs, perhaps paste a relevant portion, while making sure there's no sensitive data in there. Look for failed authentication / login attempts.

**Comment by SISolutions** [comment]
NC 10.0.6
Bookmarks  0.9.0 there is no any new update available.

NC log : Info - core - Bruteforce attempt from "my ip" detected for action
"login".

John P

**Comment by marcelklehr** [comment]
That's it, floccus requires nextcloud bookmarks app with at least version 0.10. See https://apps.nextcloud.com/apps/bookmarks

**Comment by marcelklehr** [comment]
Closing due to lack of activity. I hope it works for you, now :)

**Comment by SISolutions** [comment]
Nop its not working. Except that why you close an issue while still exists?

Friendly speaking.

**Comment by marcelklehr** [comment]
I'm sorry, John. I closed the issue, because I thought I had found its cause: an outdated version of the bookmarks app. You definitely need v0.10. I take it you have installed v0.10 now and it still doesn't work? Then lets reopen and investigate some more.

**Comment by SISolutions** [comment]
NC 12.0.3
Ubuntu 14.04 lts
Firefox 56

Its installed but nothing happens

![screenshot from 2017-11-01 23-34-22](https://user-images.githubusercontent.com/10695841/32299417-334af71a-bf5e-11e7-93c6-5b1eb46bfb38.png)

**Comment by marcelklehr** [comment]
Thanks for the update! This is the old version, which doesn't have any status indicator, yet, so there won't be happening anything even if it worked. I suggest you install the latest beta (see #27) I will hopefully get around to releasing the next version soon, if the beta works for you (this issue is the last blocker ;) )

**Comment by SISolutions** [comment]
Good morning Marcel,

Ok i will install the beta and will try it.
Yep lets home its our last blocker ;)

Thank you for your quick responce.

JP

John Pagourtzis | SISolutions
jp@sisolutions.gr
http://sisolutions.gr
Mob: +306936014031

**Comment by SISolutions** [comment]
Installed what you see in the attachment and again nothing is working.
NC 12.0.3 - Ubuntu 14.04 LTS
![screenshot from 2017-11-10 11-25-12](https://user-images.githubusercontent.com/10695841/32652553-47a4468e-c60d-11e7-8d18-e862b1f69347.png)

**Comment by marcelklehr** [comment]
if the floccus options are unstyled as they are in your screenshot that means that you have not installed the latest beta, I'm afraid. (Note that you probably cannot permanently install the latest beta on firefox, but you need to load it temporarily as pointed out in #27)

**Comment by marcelklehr** [comment]
Hey there, have you been able to try the beta?

**Comment by SISolutions** [comment]
no i havent.

Most of the NC apps are very buggy and half working or not working at all. At this time i need apps that work so i can have a productive day. So i use NC only for upload/download files and some times sharing and even that its not stable or fast enough but no time to migrate at the moment somewhere else.
Unfortunately i dont have time to test your solution. Maybe i will try some day but thats not gona happen now.

Keep up the good work.

**Comment by marcelklehr** [comment]
Hey John,

I've updated floccus on addons.mozilla.com, so you could test it now without installing any beta version. From what I've gathered it works pretty well and hopefully won't cause you more headache :)
I'm closing this again for now. You're always welcome to drop a note here or open a new issue if you happen to give it another try and still hit problems.

Cheers!
