### ISSUE TITLE
Beta phase for v2.0.0

### ISSUE THREAD

**Issue by marcelklehr** [marcelklehr/floccus#46]
Hello there,

anyone who's up for a bit of testing in order to get an earlier glimpse at the new features of the upcoming floccus (folder sync ;)) version can follow the guide below.

Folders are now synced by utilizing specialized tags that contain the path of the folder the bookmark is in, e.g. `floccus:>your>folder`.

## Installation

**Note:** You'll need ~~the latest changes of the bookmarks app on the server as well.~~ version 0.11.0 of the bookmarks app in your nextcloud .

### Chrome (separate testing installation)
* Download the build here: https://github.com/marcelklehr/floccus/releases/tag/v2.0.0-beta.2
* Unzip the zip file
* In chrome go to `chrome://extensions/`
* Enable developer mode
* Click `Load unpacked extension` and select the root folder of the floccus build

### Chrome (direct upgrade)
* Download the crx build here: https://github.com/marcelklehr/floccus/releases/tag/v2.0.0-beta.2
* In chrome go to `chrome://extensions/`
* Drop the `.crx` file into the page to install

### Firefox (separate testing installation; cannot upgrade)
* Download the zip build here: https://github.com/marcelklehr/floccus/releases/tag/v2.0.0-beta.2
* Unzip the zip file
* In firefox go to `about:debugging`
* Click `Load tempoprary addon` and select the manifest file in the root folder of the floccus build

## Debugging
In case you experience problems, file an issue on this repo. In order to aid in debugging, please provide client-side logs:

#### Firefox
* Go to `about:debugging`
* click on `debug` button next to floccus entry
* go to floccus options and make sure the account of your choice is connected
* trigger a sync by clicking on `force Sync` for the account of your choice.
* go back to the inspector window and copy the logs after waiting approx. 2mins
* paste the logs *somewhere else* removing any sensbile info and link to the site here (e.g. use https://pastebin.com)

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* go to floccus options and make sure the account of your choice is connected
* trigger a sync by clicking on `force Sync` for the account of your choice
* go back to the inspector window and copy the logs after waiting approx. 2mins
* paste the logs *somewhere else* removing any sensbile info and link to the site here (e.g. use https://pastebin.com)

Cheers!
Marcel

**Comment by marcelklehr** [comment]
It turns out the choice of magic string (`__floccus-path:`) was a bit too verbose, it leads some users to think there's something wrong and clutters up the UI with useless text, so I'm thinking about changing it to something like `floccus:/foo/bar`

**Comment by kgraefe** [comment]
Sounds good to me.

**Comment by jookk** [comment]
I getting some error in chrome. 
Error loading extension
Impossible to load extension from source folder...
Impossible to load page on backgroud „dist/html/background.html“.

tried from unpacked zip

**Comment by marcelklehr** [comment]
@jookk ah, my bad. I forgot to add the zipped build to the release (the zipped source will not work). Here you go :)

**Comment by marcelklehr** [comment]
@jookk Yes, ideally you would be able to install floccus on firefox for android (see #3). Until Firefox for android supports this, you can make use of the following android app: https://github.com/theScrabi/OCBookmarks It's not the same, but it works.

**Comment by marcelklehr** [comment]
Unfortunately, I've discovered that having tags with slashes in them breaks the nextcloud REST API, due to Apache decoding even the urlencoded slashes and treating them as path separators. The result is that people cannot delete the tags floccus sets. It's still possible to remove tags from a bookmark, but deleting a tag from the app directly is not possible when it contains slashes. (see https://github.com/nextcloud/bookmarks/issues/441)

So, I'm also considering changing the path separator for these tags, even though I'm unhappy about that. I'm thinking maybe `>`, as it indicates a direction? so, e.g. `floccus:>blog articles>technology>` instead of `floccus:/blog articles/technology/`.

**Comment by SoftwareEngineer** [comment]
Hi!
I tried your latest dev branch and I am hitting the following error intermittently:

`Fetching bookmarks Object { type: "nextcloud", url: "https://www/nextcloud", username: "user", password: "password", syncing: true, error: "creatUrl is not defined" }
`
Any idea what is going wrong? Sometimes when I start all over and just add one bookmark it fails like this. Other times it works....

**Comment by marcelklehr** [comment]
Hey @SoftwareEngineer 
thanks for reporting this. I've just fixed the typo :)

**Comment by SoftwareEngineer** [comment]
@marcelklehr Appreciate the quick fix! Now it starts to sync but then I run into the following error (no message found in nextcloud.log):
`Fetching bookmarks Object { type: "nextcloud", url: "https://www/nextcloud", username: "user", password: "pass", syncing: true, error: "nextcloud API returned error" }`

But then I also see the following afterwards:
`Object { data: Array[274], status: "success" }`

**Comment by marcelklehr** [comment]
@SoftwareEngineer Since you appear to be acquainted with the browser dev tools, you could check the Network tab to see exactly what happens to the request that gets an error response.

**Comment by SoftwareEngineer** [comment]
@marcelklehr So I found one bookmark causing an error presumably because there were some strange characters in the title ("â€”"). So I deleted it and removed everything and synced again. I am still getting "error" in the GUI but don't see an error in the Network tab anymore after removing the mentioned bookmark. However, I am sync'ing a lot of bookmarks and my server is fairly slow so it is taking a long time. Do you have a timeout that is kicking in or something that is causing it to show error in the GUI?

**Comment by marcelklehr** [comment]
@SoftwareEngineer Can you post the error caused by the bookmark with the strange title? regarding the large set of bookmarks, I think it's unlikely that's causing problems. There might simply be other client-side bugs. What does the error message say? (Hover over the Error in the GUI.)

**Comment by SoftwareEngineer** [comment]
@marcelklehr Regarding strange title issue. Here is the request:

`          "postData": {
            "mimeType": "multipart/form-data; boundary=---------------------------164086561520606906801937991141",
            "params": [],
            "text": "-----------------------------164086561520606906801937991141\r\nContent-Disposition: form-data; name=\"url\"\r\n\r\nfile:///home/abc/nextcloud/file.html\r\n-----------------------------164086561520606906801937991141\r\nContent-Disposition: form-data; name=\"title\"\r\n\r\nFile's â€” abc\r\n-----------------------------164086561520606906801937991141\r\nContent-Disposition: form-data; name=\"item[tags][]\"\r\n\r\nfloccus:/foldername/\r\n-----------------------------164086561520606906801937991141--\r\n"
`
Response:
`        "response": {
          "status": 400,
          "statusText": "Bad request",
          "httpVersion": "HTTP/1.1",
          "headers": [
                        ...
          ],
          "cookies": [],
          "content": {
            "mimeType": "application/json; charset=utf-8",
            "size": 18,
            "text": "{\"status\":\"error\"}"
          },
          "redirectURL": "",
          "headersSize": 2282,
          "bodySize": 2300
        },
`

**Comment by SoftwareEngineer** [comment]
@marcelklehr Thanks for fixing the issue concerning the creation of bookmarks on the server! It seems to be working now. The only issue is the one with the strange title but that is not a big deal at all. The title should be cleaned up anyway.

However, one thing is that when sync'ing the bookmarks firefox pegs the cpu @ 100% and firefox becomes very unresponse. Is there something that can be done about that?

**Comment by marcelklehr** [comment]
@SoftwareEngineer Good news: The problem with the title is already fixed in nextcloud/bookmarks#424 :tada: (Without intending to :D)

I'll see what I can do about that cpu blockage :)

**Comment by marcelklehr** [comment]
Beta 2 is out now, with custom folders, polished UI, the new tag prefix, and smarter syncing. :tada:

**Comment by marcelklehr** [comment]
The beta should work with the bookmarks app out of the box, now, starting with the new version: v0.11.0 :)

**Comment by ffuentes** [comment]
Hi,
i'm getting issues with spaces and latin chars in folders.

Nextcloud version: 13.0.0
Bookmarks app: 0.11.0
Floccus version: 2.0.0 beta2

![floccus latin chars](https://user-images.githubusercontent.com/17456/37371938-e8666b22-26ef-11e8-9698-a487c4fd22a1.PNG)

It does sync (and freezes! for about half a minute).

**Comment by phreaker0** [comment]
I discovered the develop branch some days ago and finally can sync my bookmarks again across my devices and browsers. Big thx for your work here. The issues I came across:
- if a folder is renamed, the old named one is left empty on the other devices, it should be deleted if the last bookmark was removed from it
- bookmarks with file:/// protocol or javascript:( ones won't work and make the sync stop because they can't be created (I guess the bookmarks app won't allow them). The error message is misleading as it states that there is an error with signing into nextcloud. The server responds with 400 Bad Request in that case. It would be great if the error message says that the server is rejecting the specific bookmark and if the sync won't abort because some bookmarks fail to be created.

**Comment by marcelklehr** [comment]
Thanks for the feedback, folks!

@ffuentes The %-encoded characters are by design for now, but I will fix that. The freezing is fixed already, but hasn't made it into the beta 2 release :)

@phreaker0 I will look into the automatic folder removal. I would rather fix the problems with acceptance of protocols on the server-side (the complete break of the sync process is a safety measure for now, but will probably be a good opportunity for improvement). The error message is fixed now, though. :)

**Comment by phreaker0** [comment]
You mean that the error message should be fixed in the current develop HEAD, because I'm running that :-)

**Comment by marcelklehr** [comment]
@phreaker0 Sorry, I meant I've fixed it locally. I've just pushed to the repo, so if you pull from the repo it should be fixed for you, too :)

**Comment by marcelklehr** [comment]
btw, don't run develop in a production environment, mind you, it will eat your bookmarks! :D

**Comment by phreaker0** [comment]
thx.
no risk no fun :-D I'm aware of the bleeding edge status, I have backups for that.

**Comment by phreaker0** [comment]
i like the new status icons and the folder removal works for me, great stuff!

**Comment by marcelklehr** [comment]
So, on the protocol front we decided to not add file or javascript to the accepted protocols on the server: https://github.com/nextcloud/bookmarks/issues/454

**Comment by marcelklehr** [comment]
I think I'll opt to ignore those bookmarks then, since throwing errors might be useless as most users 
 probably don't even want to remove those bookmarks.

**Comment by phreaker0** [comment]
That would be nice, as I could move back the unsupported bookmarks to the toolbar.

**Comment by marcelklehr** [comment]
.......aaand it's out there. v2.0.0 is released! Thanks for your help testing the changes :heart: :)
