### ISSUE TITLE
E022: Folder #-1[undefined] supposedly contains non-existent bookmark 205

### ISSUE THREAD

**Issue by amo13** [marcelklehr/floccus#511]
I am having the E022 error that I have seen discussed in #401.
I just installed and set up floccus for the first time after I updated my bookmarks app in nextcloud to the current version. My nextcloud is also latest stable version. 
In my NC, I have imported my bookmarks from firefox into a "Imported bookmarks" folder and otherwise there is nothing on the nextcloud side. In Floccus I told to sync my local (firefox) "Bookmark menu" folder with the remote "Firefox" folder.
I also tried creating the remote folder in the bookmarks nextcloud app, but the error is the same. 
I just dropped my log in the floccus log file drop.

Any advice would be greatly appreciated, thanks in advance!

**Comment by SenaidaHdez** [comment]
Also happens to me. In case it helps, I recently updated to Ubuntu 20.04. Looking for a solution too!
Also, I would like an automatic exporting function of a html, and an automatic html importing function to nextcloud. That would let the tags to be passed to nextcloud automatically, and the other way around.

**Comment by marcelklehr** [comment]
The recent bookmarks update has caused some issues. An update for the app will likely fix the error.

**Comment by amo13** [comment]
Oh, now I see that you are also the author of the nextcloud app. Let me know if there is something I can do to help fixing it. 
Thanks for your work on all this!

**Comment by marcelklehr** [comment]
Bookmarks v3.0.6 might fix this, I haven't verified this myself, but it's possible.

**Comment by rigrig** [comment]
No such luck it seems :-(
I updated Bookmarks to v3.0.6, in Floccus 4.1.0 removed my account and created a new one, sync still gives
`E022: Folder #-1[undefined] supposedly contains non-existent bookmark 148`
 Tried in both Firefox and Chromium.

**Comment by marcelklehr** [comment]
Correction: v3.0.7 should fix this. Once you've updated, click delete all bookmarks in nextcloud again.

**Comment by rigrig** [comment]
After updating to 3.0.7 and pressing "delete all bookmarks" a few times I still got the error, even uninstalling+reinstalling the app didn't help.
Uninstalling the app, manually deleting all traces of it from the database, and then reinstalling fixed it though.

**Comment by marcelklehr** [comment]
> Uninstalling the app, manually deleting all traces of it from the database, and then reinstalling fixed it though.

I would not recommend that as of now, unless you are in a hurry.

v3.0.8 is out now and has a repair step that selectively weeds out traces of bookmarks that clog up the sync.

**Comment by rigrig** [comment]
Oh right, that wasn't meant as advice, more as feedback that a fresh 3.0.7 install worked, but that somehow uninstalling+reinstalling did not fix it.

**Comment by marcelklehr** [comment]
Yeah, uninstalling currently doesn't remove data from the db.

**Comment by marcelklehr** [comment]
There are [reports](https://github.com/nextcloud/bookmarks/issues/1013) that v3.0.8 of the bookmarks app fixes this issue.

**Comment by amo13** [comment]
> There are [reports](https://github.com/nextcloud/bookmarks/issues/1013) that v3.0.8 of the bookmarks app fixes this issue.

I can confirm that. Thank you for for work on this!

**Comment by Simplenuity** [comment]
Hi there,
Many thanks for this very useful piece of software.

I'm facing the same/similar(?) error now with 
* four browsers (Google Chrome, Firefox, Opera, Vivaldi) running on Linux
and 
* FLOCCUS V4.2.5, after updating as well as after a complete new installation.

Error message:
`E022: Folder #7672[door handle spring] supposedly contains non-existent bookmark 62551`

Any help would be highly appreciated.
Kind regards

**Comment by marcelklehr** [comment]
@Simplenuity Could you open a new issue with all the necessary details? :blue_heart:

**Comment by Simplenuity** [comment]
done :)
