### ISSUE TITLE
Can't change password?

### ISSUE THREAD

**Issue by Whissi** [marcelklehr/floccus#568]
**Describe the bug**
I created a new app password in Nextcloud.
I now want to use that password in floccus but after saving changed settings, next sync will just fail with "**E018: Couldn't authenticate with the server**" -- nothing in logs.

**To Reproduce**
1. Set up floccus in browser.
2. Make sure it's working and can sync.
3. Now revoke used app password and create a new one.
4. Open floccus settings, go to account details, paste new app password into password field and click Save button below.
5. Back in floccus settings start sync.

**Expected behavior**
Floccus should be able to continue synchronizing using new credentials.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Tried in Firefox 77 and Microsoft Edge 84
 - Floccus version: 4.2.1
 - Floccus sync method: Nextcloud Bookmarks

**Server (please complete the following information):**
 - Nextcloud version: 19.0.0

**Comment by marcelklehr** [comment]
This should be resolved in the latest release.

**Comment by Whissi** [comment]
Do you know when this update will appear in Microsoft store?

**Comment by marcelklehr** [comment]
Probably today or tomorrow, I'm guessing. It's in review right now. :)

**Comment by Whissi** [comment]
Still not working with 4.2.5 in Edge. When I change password and start new sync, it will always end with `E018: Couldn't authenticate with the server`. I made the same account change in Firefox and Firefox is able to sync. Floccus logs from Edge:
```
2020-06-18T11:15:55.301Z Starting sync process for account myusername@cloud.example.org
2020-06-18T11:15:55.372Z Using normal strategy
2020-06-18T11:15:55.394Z Overriding title of built-in node 1 Favorites bar => Bookmarks Bar
2020-06-18T11:15:55.395Z Overriding title of built-in node 2 Other favorites => Other Bookmarks
2020-06-18T11:16:20.822Z Fetching bookmarks
2020-06-18T11:16:46.185Z Syncing failed with E018: Couldn't authenticate with the server
2020-06-18T11:16:48.266Z Starting sync process for account myusername@cloud.example.org
2020-06-18T11:16:48.332Z Using normal strategy
2020-06-18T11:16:48.352Z Overriding title of built-in node 1 Favorites bar => Bookmarks Bar
2020-06-18T11:16:48.353Z Overriding title of built-in node 2 Other favorites => Other Bookmarks
2020-06-18T11:17:13.717Z Fetching bookmarks
2020-06-18T11:17:39.080Z Syncing failed with E018: Couldn't authenticate with the server
2020-06-18T11:15:55.301Z Starting sync process for account myusername@cloud.example.org
2020-06-18T11:15:55.372Z Using normal strategy
2020-06-18T11:15:55.394Z Overriding title of built-in node 1 Favorites bar => Bookmarks Bar
2020-06-18T11:15:55.395Z Overriding title of built-in node 2 Other favorites => Other Bookmarks
2020-06-18T11:16:20.822Z Fetching bookmarks
2020-06-18T11:16:46.185Z Syncing failed with E018: Couldn't authenticate with the server
2020-06-18T11:16:48.266Z Starting sync process for account myusername@cloud.example.org
2020-06-18T11:16:48.332Z Using normal strategy
2020-06-18T11:16:48.352Z Overriding title of built-in node 1 Favorites bar => Bookmarks Bar
2020-06-18T11:16:48.353Z Overriding title of built-in node 2 Other favorites => Other Bookmarks
2020-06-18T11:17:13.717Z Fetching bookmarks
2020-06-18T11:17:39.080Z Syncing failed with E018: Couldn't authenticate with the server
```
