### ISSUE TITLE
Error E020 during sync

### ISSUE THREAD

**Issue by fermat2a** [marcelklehr/floccus#664]
**Describe the bug**

I am using floccus firefox addon to sync bookmarks to Nextcloud. Since some days I get following error:

```
E020: Antwort des Servers konnte nicht gelesen werden. Ist die Bookmarks App auf Ihrem Server installiert? JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

**To Reproduce**
1. Go to floccus addon
2. Click on 'Jetzt synchronisieren' (sync now)
3. See error

**Expected behavior**
Floccus should sync the bookmarks.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser firefox
 - Browser Version 80.0.1 (64-Bit)
 - Floccus version: 4.3.0
 - Floccus sync method: nextcloud bookmarks

**Server (please complete the following information):**
 - OS: Ubuntu 18.04
 - Nextcloud version: 19.0.3
 - Bookmarks app version: 3.4.1

**Debug log**
With each sync following appears in debug log:

```
2020-10-03T21:46:57.684Z Starting sync process for account fermat@nextcloud.drecksnetz.ddnss.de
2020-10-03T21:46:57.743Z Using normal strategy
2020-10-03T21:46:58.656Z Fetching bookmarks
2020-10-03T21:46:59.630Z Syncing failed with E020: Antwort des Servers konnte nicht gelesen werden. Ist die Bookmarks App auf Ihrem Server installiert?
JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

- [x] Debug log provided

[floccus-4.3.0-2020-10-04.log](https://github.com/marcelklehr/floccus/files/5322728/floccus-4.3.0-2020-10-04.log)

**Additional context**

I sync server folder `/privat` to bookmark folder `Nextcloud (fermat@nextcloud.drecksnetz.ddnss.de)`.

In Nextcloud log I see following error:

```
[index] Error: Exception: Call to undefined function OCA\Bookmarks\Db\array_first() at <<closure>>

0. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 137
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmarks\Co ... {}, "getBookmarks")
1. /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Bookmarks\ ... r", "getBookmarks", OC\AppFramework\ ... {}, {_route: "bookma ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "bookma ... "})
3. /var/www/html/nextcloud/lib/private/Route/Router.php line 297
   call_user_func(OC\AppFramework\ ... {}, {_route: "bookma ... "})
4. /var/www/html/nextcloud/lib/base.php line 1012
   OC\Route\Router->match("/apps/bookmarks/public/rest/v2/bookmark")
5. /var/www/html/nextcloud/index.php line 37
   OC::handleRequest()

GET /index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300
from 192.168.135.54 by fermat at 2020-10-04T05:42:03+00:00
```
and 

```
[index] Error: Exception: Call to undefined function OCA\Bookmarks\Db\array_first() at <<closure>>

0. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 137
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmarks\Co ... {}, "hashFolder")
1. /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Bookmarks\ ... r", "hashFolder", OC\AppFramework\ ... {}, {folderId: "-1", ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({folderId: "-1", ... "})
3. /var/www/html/nextcloud/lib/private/Route/Router.php line 297
   call_user_func(OC\AppFramework\ ... {}, {folderId: "-1", ... "})
4. /var/www/html/nextcloud/lib/base.php line 1012
   OC\Route\Router->match("/apps/bookmarks ... h")
5. /var/www/html/nextcloud/index.php line 37
   OC::handleRequest()

GET /index.php/apps/bookmarks/public/rest/v2/folder/-1/hash
from 192.168.135.54 by fermat at 2020-10-04T05:42:02+00:00
```
every minute, so every time floccus tries to sync.

**Comment by gerroon** [comment]
Hi 

I have this error too. Is this an issue with the extension or Nextcloud?

**Comment by marcelklehr** [comment]
This is an issue with the nextcloud bookmarks app. A fix has been released.

**Comment by gerroon** [comment]
Hi

I installed 3.4.3 unstable for NC 19 (manually replaced the bookmarks app) from the releases and I still seem to have this issue.

```
E020: Could not parse server response. Is the bookmarks app installed on your server? JSON.parse: unexpected character at line 1 column 1 of the JSON data 

```

**Comment by marcelklehr** [comment]
@gerroon Sorry for the late response, I somehow missed your comment. In this case the culprit is likely the emoji in the bookmark title. Make sure your nextcloud database uses utf8_mb4 encoding.

**Comment by gerroon** [comment]
@marcelklehr 

I converted my database and the tables to utf8_mb4  and I still get this error unfrotunately.

phpmyadmin listing

`nextcloud 	utf8mb4_bin `
